import os
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

_client = None


def _get_client():
    global _client
    if _client is None:
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
            raise EnvironmentError(
                "OPENAI_API_KEY not found. Add it to your .env file."
            )
        _client = OpenAI(api_key=api_key)
    return _client


AI_DISCLOSURE = (
    "✨ Generated by AI (GPT-4o) — please review before use. "
    "NewLeaf uses AI to assist, not replace, human judgment."
)


def call_gpt(system_prompt: str, user_message: str) -> str:
    client = _get_client()
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ],
        max_tokens=800,
        temperature=0.7,
    )
    return response.choices[0].message.content
